version: '3.1'

services:
#  mysql:
#    image: mysql
#    restart: always
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - '3308:3306'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'